### ISSUE TITLE
Use HDD Highest Temp

### ISSUE THREAD

**Issue by BadCo-NZ** [petersulyok/smfc#1]
Hi there,

A mate and I have been playing with this script, and it works well, thanks for your effort!

We were wondering though, if it would be possible to change fan speed based on the drive with the highest temp instead of the average temp?

Often there is one or two drives that run hotter then the rest, but they get lost in the 'average' and end up staying above the threshold.

Thanks

**Comment by petersulyok** [comment]
Hi,

Thanks for the proposal. It is an interesting idea. 
My experience is that the airflow is not even for all HDs, and this might be the primary reason why they have different temperatures. You may want to improve this as well.
Let me think about this how to implement.
Cheers,

Peter

**Comment by BadCo-NZ** [comment]
Hi Peter,

Yes, definitely airflow plays a part in the temperature variation between hard drives.

I am using a Supermicro SC825 which has good fans and airflow, but there is still a variation of 6c between my eight spinning hard drives (38c on the coldest, 44c on the hottest).

I look forward to what you come up with :)

**Comment by petersulyok** [comment]
Please take a look into this [commit](https://github.com/petersulyok/smfc/commit/8795078bcc15ee93299bc4743631c3dbee252790). It implements multiple ways of the temperature calculation for both HDs and CPUs.

**Comment by petersulyok** [comment]
This feature request has been implemented in release v1.1.0.

**Comment by BadCo-NZ** [comment]
Nice work @petersulyok, unfortunately I haven't had a chance to test it yet, but will report back when I do.
