### ISSUE TITLE
Document behavior with ULNA

### ISSUE THREAD

**Issue by emansom** [petersulyok/smfc#12]
When pairing Noctua fans with Ultra Low Noise Adapters, the default lower threshold of 35% isn't enough.

This threshold needs to be upped to 45% to not upset the firmware, when using ULNA.

Describing this in the README will aid others in debugging and getting their Supermicro systems whisper quiet.

**Comment by petersulyok** [comment]
Thanks for the suggestion, I will do that.

**Comment by petersulyok** [comment]
The suggestion is part of the documentation now. Thanks for that!
