### ISSUE TITLE
Error starting daemon

### ISSUE THREAD

**Issue by rkarlsba** [petersulyok/smfc#14]
This is on latest Debian 11 Bullseye. Any idea?

I get the following error:

```
# /opt/smfc/smfc.py -c /opt/smfc/smfc.conf -l 3 -o 1
DEBUG: Logging module was initialized with:
DEBUG:    log_level = 3
DEBUG:    log_output = 1
DEBUG: Command line arguments:
DEBUG:    original arguments: /opt/smfc/smfc.py -c /opt/smfc/smfc.conf -l 3 -o 1
DEBUG:    parsed config file = /opt/smfc/smfc.conf
DEBUG:    parsed log level = 3
DEBUG:    parsed log output = 1
DEBUG: Configuration file (/opt/smfc/smfc.conf) loaded
DEBUG: Ipmi module was initialized with :
DEBUG:    command = /usr/bin/ipmitool
DEBUG:    fan_mode_delay = 10
DEBUG:    fan_level_delay = 2
ERROR: invalid literal for int() with base 10: ''.
```

smfc.conf:
```
# vim:isfname-==
#
#   smfc.conf
#   smfc service configuration parameters
#


[Ipmi]
# Path for ipmitool (str, default=/usr/bin/ipmitool)
command=/usr/bin/ipmitool
# Delay time after changing IPMI fan mode (int, seconds, default=10)
fan_mode_delay=10
# Delay time after changing IPMI fan level (int, seconds, default=2)
fan_level_delay=2

[CPU zone]
# Fan controller enabled (bool, default=0)
enabled=1
# Number of CPUs (int, default=1)
count=1
# Calculation method for CPU temperatures (int, [0-minimum, 1-average, 2-maximum], default=1)
temp_calc=1
# Discrete steps in mapping of temperatures to fan level (int, default=6)
steps=6
# Threshold in temperature change before the fan controller reacts (float, C, default=3.0)
sensitivity=3.0
# Polling time interval for reading temperature (int, sec, default=2)
polling=2
# Minimum CPU temperature (float, C, default=30.0)
min_temp=30.0
# Maximum CPU temperature (float, C, default=60.0)
max_temp=65.0
# Minimum CPU fan level (int, %, default=35)
min_level=10
# Maximum CPU fan level (int, %, default=100)
max_level=100
# Optional parameter, it will be generated automatically (can be used for testing and in special cases).
# Path for CPU sys/hwmon/coretemp file(s) (str multi-line list, default=/sys/devices/platform/coretemp.0/hwmon/hwmon*/temp1_input)
# hwmon_path=/sys/devices/platform/coretemp.0/hwmon/hwmon*/temp1_input
#            /sys/devices/platform/coretemp.1/hwmon/hwmon*/temp1_input


[HD zone]
# Fan controller enabled (bool, default=0)
enabled=1
# Number of HDs (int, default=1)
count=20
# Calculation of HD temperatures (int, [0-minimum, 1-average, 2-maximum], default=1)
temp_calc=1
# Discrete steps in mapping of temperatures to fan level (int, default=4)
steps=4
# Threshold in temperature change before the fan controller reacts (float, C, default=2.0)
sensitivity=2.0
# Polling interval for reading temperature (int, sec, default=10)
polling=10
# Minimum HD temperature (float, C, default=32.0)
min_temp=10.0
# Maximum HD temperature (float, C, default=46.0)
max_temp=46.0
# Minimum HD fan level (int, %, default=35)
min_level=10
# Maximum HD fan level (int, %, default=100)
max_level=100
# Names of the HDs (str multi-line list, default=)
# These names MUST BE specified in '/dev/disk/by-id/...'' form!
# See /dev/disk/by-id for a list
hd_names=/dev/disk/by-id/ta-ST8000VN0022-2EL112_ZA15MZ6H
	 /dev/disk/by-id/ta-ST8000VN0022-2EL112_ZA18AGTZ
	 /dev/disk/by-id/ta-ST8000VN0022-2EL112_ZA18YT0D
	 /dev/disk/by-id/ta-ST8000VN0022-2EL112_ZA18ZHAD
	 /dev/disk/by-id/ta-ST8000VN0022-2EL112_ZA19LB36
	 /dev/disk/by-id/ta-ST8000VN0022-2EL112_ZA19VNKB
	 /dev/disk/by-id/ta-ST8000VN0022-2EL112_ZA19XF88
	 /dev/disk/by-id/ta-ST8000VN0022-2EL112_ZA19Z568
	 /dev/disk/by-id/ta-ST8000VN0022-2EL112_ZA19Z6RH
	 /dev/disk/by-id/ta-ST8000VN0022-2EL112_ZA1E0VC6
	 /dev/disk/by-id/ta-ST8000VN0022-2EL112_ZA1E116P
	 /dev/disk/by-id/ta-ST8000VN0022-2EL112_ZA1E3V2G
	 /dev/disk/by-id/ta-ST8000VN0022-2EL112_ZA1FB9FQ
	 /dev/disk/by-id/ta-ST8000VN0022-2EL112_ZA1FECM9
	 /dev/disk/by-id/ta-ST8000VN0022-2EL112_ZA1FH7AX
	 /dev/disk/by-id/ta-ST8000VN004-2M2101_WKD04YD5
	 /dev/disk/by-id/ta-ST8000VN004-2M2101_WKD19NFM
	 /dev/disk/by-id/ta-ST8000VN004-2M2101_WKD1F7WW
	 /dev/disk/by-id/ta-Samsung_SSD_860_EVO_1TB_S3Z9NB0K731782M
	 /dev/disk/by-id/ta-Samsung_SSD_860_EVO_1TB_S3Z9NB0K731786Y
# Optional parameter, it will be generated automatically (can be used for testing and in special cases).
# Path for HD sys/hwmon/drivetemp file(s) (str multi-line list, default=/sys/class/scsi_disk/0:0:0:0/device/hwmon/hwmon*/temp1_input)
# hwmon_path=/sys/class/scsi_disk/0:0:0:0/device/hwmon/hwmon*/temp1_input
#            /sys/class/scsi_disk/1:0:0:0/device/hwmon/hwmon*/temp1_input
# Standby guard feature for RAID arrays (bool, default=0)
standby_guard_enabled=0
# Number of HDs already in STANDBY state before the full RAID array will be forced to it (int, default=1)
standby_hd_limit=1
# Path for 'smartctl' command (str, default=/usr/sbin/smartctl)
smartctl_path=/usr/sbin/smartctl
```

**Comment by petersulyok** [comment]
I think a string to float conversation failed in the INI file.

You might have a different decimal point in your Linux setup and that could cause a problem?
You may check your config and change the INI file based on that.
Let me know if you found something here.

**Comment by petersulyok** [comment]
Do you see any Python runtime information for this error?
I would appreciate any additional information, especially source code line number.

**Comment by rkarlsba** [comment]
This is all I get

'''
root@mediabox:~/src/git/petersulyok/smfc# python3 ./src/smfc.py -c /opt/smfc/smfc.conf -l 3 -o 1
DEBUG: Logging module was initialized with:
DEBUG:    log_level = 3
DEBUG:    log_output = 1
DEBUG: Command line arguments:
DEBUG:    original arguments: ./src/smfc.py -c /opt/smfc/smfc.conf -l 3 -o 1
DEBUG:    parsed config file = /opt/smfc/smfc.conf
DEBUG:    parsed log level = 3
DEBUG:    parsed log output = 1
DEBUG: Configuration file (/opt/smfc/smfc.conf) loaded
DEBUG: Ipmi module was initialized with :
DEBUG:    command = /usr/bin/ipmitool
DEBUG:    fan_mode_delay = 10
DEBUG:    fan_level_delay = 2
ERROR: invalid literal for int() with base 10: ''.
'''

Running this python version
'''
root@mediabox:~/src/git/petersulyok/smfc# python3 --version
Python 3.9.2
'''

**Comment by petersulyok** [comment]
OK, thx. I will debug `smfc` with your config.

**Comment by petersulyok** [comment]
You have to execute `smfc` as a root user (e.g. with sudo). `Ipmi.get_fan_mode()` function failed in line 198. The `ipmitool` command gave back this error message:

`Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0: No such file or directory`

meaning that you don't have an access right for IPMI device. I'm thinking on a more meaningful error handling here.
Thanks for catching this.

**Comment by petersulyok** [comment]
Please pull/check this commit [a371c3b536506a741c6f0599a53ead1a78fe5ad0](https://github.com/petersulyok/smfc/commit/a371c3b536506a741c6f0599a53ead1a78fe5ad0), and use root user for `smfc` execution. Let me know if you able to run service now.

**Comment by rkarlsba** [comment]
I did RTFM before I started, so everything is as root ;)

root@mediabox:~/src/git/petersulyok/smfc# python3 ./src/smfc.py -c /opt/smfc/smfc.conf -l 3 -o 1
DEBUG: Logging module was initialized with:
DEBUG:    log_level = 3
DEBUG:    log_output = 1
DEBUG: Command line arguments:
DEBUG:    original arguments: ./src/smfc.py -c /opt/smfc/smfc.conf -l 3 -o 1
DEBUG:    parsed config file = /opt/smfc/smfc.conf
DEBUG:    parsed log level = 3
DEBUG:    parsed log output = 1
DEBUG: Configuration file (/opt/smfc/smfc.conf) loaded
DEBUG: Ipmi module was initialized with :
DEBUG:    command = /usr/bin/ipmitool
DEBUG:    fan_mode_delay = 10
DEBUG:    fan_level_delay = 2
Traceback (most recent call last):
  File "/root/src/git/petersulyok/smfc/./src/smfc.py", line 921, in <module>
    main()
  File "/root/src/git/petersulyok/smfc/./src/smfc.py", line 876, in main
    old_mode = my_ipmi.get_fan_mode()
  File "/root/src/git/petersulyok/smfc/./src/smfc.py", line 200, in get_fan_mode
    raise RuntimeError(r.stderr)
RuntimeError: Unable to send RAW command (channel=0x0 netfn=0x30 lun=0x0 cmd=0x45 rsp=0xc1): Invalid command

the mobo is X8DT3 - is this an issue?

**Comment by petersulyok** [comment]
Yep. `smfc` is supporting Super Micro X9/X10/X11 motherboards.
IPMI is not implemented on your motherboard, probably.

**Comment by rkarlsba** [comment]
It most certainly is. I can read the fans etc with ipmitool 

Vennlig hilsen 

roy 
-- 
Roy Sigurd Karlsbakk 
(+47) 98013356 
-- 
I all pedagogikk er det essensielt at pensum presenteres intelligibelt. Det er et elementært imperativ for alle pedagoger å unngå eksessiv anvendelse av idiomer med xenotyp etymologi. I de fleste tilfeller eksisterer adekvate og relevante synonymer på norsk.

**Comment by petersulyok** [comment]
Smfc implements IPMI fan control [this way](https://forums.servethehome.com/index.php?resources/supermicro-x9-x10-x11-fan-speed-control.20/), and this method is not working with your X8 motherboard.

You may check this script [smx8fancontrol](https://gist.github.com/ikus060/26a33ce1e82092b4d2dbdf18c3610fde) if you have Nuvoton W83795G Super IO chip installed on your motherboard (forum discussions are [here](https://forums.servethehome.com/index.php?threads/supermicro-ipmi-fan-control.12025/post-114156)).

Actually we have similar conversation here in issue #5 for X9 motherboards, where we try to control fan speed through a kernel module. The difference is that X9 motherboard can set/get fan modes and fan threshold with IPMI. Not sure if your X8 motherboard had any of these features, you may check that.

**Comment by rkarlsba** [comment]
Thanks 

Vennlig hilsen 

roy 
-- 
Roy Sigurd Karlsbakk 
(+47) 98013356 
-- 
I all pedagogikk er det essensielt at pensum presenteres intelligibelt. Det er et elementært imperativ for alle pedagoger å unngå eksessiv anvendelse av idiomer med xenotyp etymologi. I de fleste tilfeller eksisterer adekvate og relevante synonymer på norsk.

**Comment by petersulyok** [comment]
Summary for future readers: the `smfc` service failed to start on a `Super Micro X8DT3` motherboard (originally `smfc` was implemented for `Super Micro X10` and `X11` motherboards). During the analysis of this issue an additional error message has been implemented to make this error transparent for the user.

The issue will be closed now. If there is a progress in issue #5 then it could have some hope for `X8` motherboards as well in the future.
