### ISSUE TITLE
Supermicro boards incompatible with ULNA

### ISSUE THREAD

**Issue by emansom** [petersulyok/smfc#15]
Previously I mentioned fans with ULNA (_[Ultra Low Noise Adapter](https://noctua.at/en/na-src7)_) requiring a higher minimum to not upset the IPMI.

And after a few months running in such configuration, I've had two fans (one [NF-A12x15](https://noctua.at/en/nf-a12x15-pwm) and one [NF-A12x25](https://noctua.at/en/nf-a12x25-pwm)) die on me.

Leading me to the conclusion, that with the ULNA cables, the Supermicro board is sending either too high or too low voltages to the fans.

A cautionary warning of incompatibility with ULNA cables should probably be added to the README, as well as a comment inside the configuration files.

**Comment by petersulyok** [comment]
Can you RMA them? Do you still have guarantee for them?
ULNA adapter contains only a resistor and it decrease the voltage for the fan (i.e. it spins slower generating less noise).
It is hard to imagine that Super Micro boards could have any issue with this setup. I would rather say that you were unlucky with those two fans.
Strange.

**Comment by petersulyok** [comment]
A note has been added to the documentation about this issue.
