### ISSUE TITLE
Version 2.4.0 breaks HD zone loading?

### ISSUE THREAD

**Issue by thiete** [petersulyok/smfc#18]
It seems the latest refactor of config option handling broke the HD zone? 
If using 2.4.0, the CPU zone works fine, while the HD zone configuration does not appear to initialize at all - it won't report errors in the config parameters. If I set enable=0 in the CPU zone, and enable=1 in the HD zone, the program says that no zones are enabled and exits.
Reverting to 2.3.1 both zones work as expected.

**Comment by petersulyok** [comment]
Please check v2.4.1 release.

**Comment by thiete** [comment]
Yep, fixed in 2.4.1. Thank you for the quick fix!

**Comment by petersulyok** [comment]
What is the model of your Super Micro motherboard?

**Comment by thiete** [comment]
X11SPI-TF
