### ISSUE TITLE
X12 Support?

### ISSUE THREAD

**Issue by hy4015** [petersulyok/smfc#26]
Does this program support X12 motherboard or will it support in the future?

Modle Type:
SYS -420GP.TNR X12 4U 10GPU CIE LAKE GEN4 PCIE SYSTEM

**Comment by petersulyok** [comment]
Hi @hy4015, currently we do not have any feedback on X12 compatibility, although I'm very curios.
If you have an X12 motherboard and you have some patience we can work on that.

Could you please show your motherboard on [this list](https://www.supermicro.com/en/products/motherboards/workstation-boards)? I cannot identify it based on your description.

**Comment by petersulyok** [comment]
Based on [this conversation](https://forums.servethehome.com/index.php?threads/fan-speed-control-on-supermicro-x12.35146/) X12 motherboards seem to be working. Please try to follow the installation/configuration and let me know if you stuck anywhere.

**Comment by petersulyok** [comment]
Hi @hy4015, any progress on this? Do you need any help?
