### ISSUE TITLE
Set all fans to maximum speed on exception

### ISSUE THREAD

**Issue by Zalhera** [petersulyok/smfc#32]
Hi, 

I would suggest to set all fans to maximum speed if some unhandled exception occured.
I had the service running on my server and changed one of my HDDs to a new one and started the resilvering process.
By sheer luck I had my IPMI view open and saw that my CPU was at 90C°.
The service had an exception, because in the config there was still my old HDD in the /dev/by-id config.

I think there should be a wrapper around the whole program to set all fans to maximum speed if some unhandled exception occures.

**Comment by Zalhera** [comment]
Yes exactly, I swapped one HDD for another one.
This is the exception I got in the trace:

> Nov 06 16:35:13 truenas smfc.service[1228652]: CPU zone: new level > 68.0C > [T:68.5C/L:63%]
Nov 06 16:35:17 truenas smfc.service[1228652]: CPU zone: new level > 65.0C > [T:65.33333333333333C/L:50%]
Nov 06 16:36:14 truenas smfc.py[1228652]: Traceback (most recent call last):
Nov 06 16:36:14 truenas smfc.py[1228652]:   File "/opt/smfc/smfc.py", line 1044, in <module>
Nov 06 16:36:14 truenas smfc.py[1228652]:     main()
Nov 06 16:36:14 truenas smfc.py[1228652]:   File "/opt/smfc/smfc.py", line 1039, in main
Nov 06 16:36:14 truenas smfc.py[1228652]:     my_hd_zone.run()
Nov 06 16:36:14 truenas smfc.py[1228652]:   File "/opt/smfc/smfc.py", line 540, in run
Nov 06 16:36:14 truenas smfc.py[1228652]:     current_temp = self.get_temp_func()
Nov 06 16:36:14 truenas smfc.py[1228652]:   File "/opt/smfc/smfc.py", line 484, in get_avg_temp
Nov 06 16:36:14 truenas smfc.py[1228652]:     average += self._get_nth_temp(i)
Nov 06 16:36:14 truenas smfc.py[1228652]:   File "/opt/smfc/smfc.py", line 862, in _get_nth_temp
Nov 06 16:36:14 truenas smfc.py[1228652]:     raise e
Nov 06 16:36:14 truenas smfc.py[1228652]:   File "/opt/smfc/smfc.py", line 859, in _get_nth_temp
Nov 06 16:36:14 truenas smfc.py[1228652]:     with open(self.hwmon_path[index], "r", encoding="UTF-8") as f:
Nov 06 16:36:14 truenas smfc.py[1228652]: FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/scsi_disk/0:1:63:0/device/hwmon/hwmon10/temp1_input'
Nov 06 16:36:14 truenas systemd[1]: smfc.service: Main process exited, code=exited, status=1/FAILURE
Nov 06 16:36:14 truenas systemd[1]: smfc.service: Failed with result 'exit-code'.
Nov 06 16:36:14 truenas systemd[1]: smfc.service: Consumed 1min 30.694s CPU time.
Nov 06 17:32:21 truenas systemd[1]: Started smfc.service - Super Micro Fan Control.

**Comment by petersulyok** [comment]
Hi @Zalhera, the new release v3.2.0 contains this fix. Please test it and give a feedback if possible.

**Comment by Zalhera** [comment]
I tested it using the new version, but unfortunately it didn't work.
I changed the name of one of my HDDs in the config to simulate the replacement of the drive and the service stopped, but did not set the fans to maximum speed.

Here is the trace of the crash:

> Nov 08 21:50:30 truenas smfc.py[1969828]: Traceback (most recent call last):
Nov 08 21:50:30 truenas smfc.py[1969828]:   File "/opt/smfc/smfc.py", line 1055, in <module>
Nov 08 21:50:30 truenas smfc.py[1969828]:     main()
Nov 08 21:50:30 truenas smfc.py[1969828]:   File "/opt/smfc/smfc.py", line 1031, in main
Nov 08 21:50:30 truenas smfc.py[1969828]:     my_hd_zone = HdZone(my_log, my_ipmi, my_config)
Nov 08 21:50:30 truenas smfc.py[1969828]:   File "/opt/smfc/smfc.py", line 732, in __init__
Nov 08 21:50:30 truenas smfc.py[1969828]:     super().__init__(
Nov 08 21:50:30 truenas smfc.py[1969828]:   File "/opt/smfc/smfc.py", line 394, in __init__
Nov 08 21:50:30 truenas smfc.py[1969828]:     self.build_hwmon_path(hwmon_path)
Nov 08 21:50:30 truenas smfc.py[1969828]:   File "/opt/smfc/smfc.py", line 807, in build_hwmon_path
Nov 08 21:50:30 truenas smfc.py[1969828]:     disk_name = os.path.basename(os.readlink(self.hd_device_names[i]))
Nov 08 21:50:30 truenas smfc.py[1969828]: FileNotFoundError: [Errno 2] No such file or directory: '/dev/disk/by-id/ata-ST16000NM001G-2KK103_ZL2KGR10xx'
Nov 08 21:50:30 truenas systemd[1]: smfc.service: Main process exited, code=exited, status=1/FAILURE
Nov 08 21:50:30 truenas systemd[1]: smfc.service: Failed with result 'exit-code'.

**Comment by petersulyok** [comment]
In `v3.2.0` release the implementation tried to handle runtime changes only (an initial good configuration was changed and failed). You tested a different situation (i.e. a bad initial configuration).
I checked the implementation again and in `v3.3.0` release all possible exit conditions and exceptions are covered. Precisely, if the service is able control IPMI properly (i.e. `ipmitool` is functional) then for all exception and run-time errors the fans will be set back to 100% speed.
Could you please check it again? I think it will be better now.

**Comment by Zalhera** [comment]
@petersulyok with the v3.3.0 release everything looks great to me.
I tested restarting after a wrong configuration and the fans are set to maximum speed.
Tomorrow I will try to produce a runtime error again, but I'm sure it will work as intended.
