### ISSUE TITLE
swapping description/config file improvement

### ISSUE THREAD

**Issue by Xyz00777** [petersulyok/smfc#38]
Hi @petersulyok would it be possible to make the description of the swapping feature a little bit better? because im slightly confused now if i should let the monitoring configs for hdd in the hdd zone and for cpu in the cpu zone when i enable the swapping or not? because i tried to swap it and i got an error message.
Maybe it would also be an idea to move the cpu temp measure and the hdd temp measure out of the zones to an additional [Temp Measure] stanza or something like that?

**Comment by petersulyok** [comment]
Hi @Xyz00777, thanks for the feedback.

The original context why this feature was created can be found in #7. This user wanted to use more fans (FAN 1,...,4) for cooling HDs and less fans (FAN A,B) for cooling the CPU. This is the opposite definition how IPMI defined its own zones.

In this feature we swap the IPMI zones (and the connected fans), not the temperature sources. There are multiple ways to implement this feature. The way, how `smfc` implemented this feature, was the simplest change in the code. Your suggestion (swapping of temperature sources) would be more complex in both coding and user configuration.

I can add some further explanation in the documentation to make it more straightforward.
I hope this explanation helped for you.

**Comment by Xyz00777** [comment]
no i thought it could propably change the temperature sources (just thought too far :D)
i think further explanations would be enough :) i have done it on my server and it worked perfectly after i understood it :) now the fans works perfectly :) i have the "problem" that i have more case fans than cpu fans (6 to 2) so it was really awesome that i was able to switch the zones :)
mutch thanks for your awesome programm again!

**Comment by petersulyok** [comment]
In release v3.5.1 the documentation is improved. Please take a look.

**Comment by Xyz00777** [comment]
looks good thanks :)
