### ISSUE TITLE
smfc service fails to start automatically after system reboot

### ISSUE THREAD

**Issue by dominikheinz** [petersulyok/smfc#39]
**Summary:**
First, let me describe my system specifications:
- CPU: AMD EPYC 7443P
- Mainboard: Supermicro H12SSL-NT
- CPU Fan(s): Arctic Freezer 4U-M (2 Fans attached to Heatsink)
- Case Fans: 3x Arctic P12 Max

I would like to use smfc to significantly lower the fan speed.
I successfully installed smfc, as described in the instructions.
I also seem to be able to adjust the fan behaviour - however, after a reboot, it seems that the smfc service fails:

```
× smfc.service - Super Micro Fan Control
     Loaded: loaded (/etc/systemd/system/smfc.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Fri 2024-08-23 18:12:35 CEST; 1min 19s ago
   Duration: 4.616s
    Process: 1156 ExecStart=/opt/smfc/smfc.py $OPTIONS (code=exited, status=1/FAILURE)
   Main PID: 1156 (code=exited, status=1/FAILURE)
        CPU: 125ms

Aug 23 18:12:31 pve smfc.py[1156]:   File "/opt/smfc/smfc.py", line 600, in __init__
Aug 23 18:12:31 pve smfc.py[1156]:     super().__init__(
Aug 23 18:12:31 pve smfc.py[1156]:   File "/opt/smfc/smfc.py", line 395, in __init__
Aug 23 18:12:31 pve smfc.py[1156]:     self.build_hwmon_path(hwmon_path)
Aug 23 18:12:31 pve smfc.py[1156]:   File "/opt/smfc/smfc.py", line 632, in build_hwmon_path
Aug 23 18:12:31 pve smfc.py[1156]:     raise ValueError(self.ERROR_MSG_FILE_IO.format(path))
Aug 23 18:12:31 pve smfc.py[1156]: ValueError: Cannot read file (/sys/devices/platform/coretemp.0/hwmon/hwmon*/temp1_input).
Aug 23 18:12:35 pve smfc.service[1156]: smfc terminated: all fans are switched back to the 100% speed.
Aug 23 18:12:35 pve systemd[1]: smfc.service: Main process exited, code=exited, status=1/FAILURE
Aug 23 18:12:35 pve systemd[1]: smfc.service: Failed with result 'exit-code'.
```

This is interesting - it tries to read temperature via coretemp, however this path does not exist.
To my understanding the coretemp module is specific to Intel CPUs.
I did not install this one.
However, I of course do have k10temp installed and loaded, since my CPU is an AMD CPU.

Is this a bug, or am I forced to load the coretemp module despite not having an Intel CPU? Seems counterintuitive to me. I assume it would probably not be able to read anything either way?
Maybe the script needs a condition to check if it needs to read the path to coretemp or k10temp? Hopefully this can be resolved, otherwise my fans will always jump back to 100% after a reboot, due to the service failing to start.

Thanks for your work on this tool, very much appreciate it! :smile:

**Comment by petersulyok** [comment]
Hi @dominikheinz, thanks for the feedback.
It seems that you use HWMON path for Intel CPU but your have AMD CPU.
Please try to use this parameter:
`hwmon_path=/sys/bus/pci/drivers/k10temp/0000*/hwmon/hwmon*/temp1_input`

The documentation said the HWMON path is autoconfigured for Intel CPUs but needs to be manually configured for AMD CPUs.
And you should not load `coretemp` kernel driver of course.

**Comment by dominikheinz** [comment]
> Hi @dominikheinz, thanks for the feedback. It seems that you use HWMON path for Intel CPU but your have AMD CPU. Please try to use this parameter: `hwmon_path=/sys/bus/pci/drivers/k10temp/0000*/hwmon/hwmon*/temp1_input`
> 
> The documentation said the HWMON path is autoconfigured for Intel CPUs but needs to be manually configured for AMD CPUs. And you should not load `coretemp` kernel driver of course.

You are absolutely correct. That is my bad on not reading properly. After explicitly specifying the `hwmon_path` as described, the temperatures are read successfully.

**Comment by petersulyok** [comment]
I'm happy to hear that. If you have more CPU cores you can add more lines for that, please check HWMON files.
