### ISSUE TITLE
Not an issue just some info..

### ISSUE THREAD

**Issue by 1stFalloutBoy** [petersulyok/smfc#40]
I noticed it was queried at one point why when setting the ipmi stuff that the values went...

1 , 2, 4 I put a message up on Serve The Home which explained it but thought I would mention it here as well..

It's because it's not a value it's a mask.

421 Binary multiplier
000 Value 0
001 Value 1
010 Value 2
100 Value 4

I don't know if this will make any difference to your development or not but now at least you have it too..

I'm the chap BTW that is presently attempting to develop a serial controlled fan controller for the Supermicro Boards to use with a controlling script.

**Comment by petersulyok** [comment]
Hi @1stFalloutBoy,

Are you referring the values of IPMI fan modes?
In the `smfc` code it is presented like this (./src/smfc.py line 147)

```
 # Constant values for IPMI fan modes:
    STANDARD_MODE: int = 0
    FULL_MODE: int = 1
    OPTIMAL_MODE: int = 2
    HEAVY_IO_MODE: int = 4

```
In the [references section](https://github.com/petersulyok/smfc/tree/main#15-references) I collected the most important links on this topic. Take a look and please let me know if you miss something important.

**Comment by 1stFalloutBoy** [comment]
Yes, it was commented by someone on STH they didn't understand why raw
commands used 1,2,4 and could not understand why it skipped 3.
