### ISSUE TITLE
reading temp from NVME drives fails on 6.1.0-27

### ISSUE THREAD

**Issue by olk** [petersulyok/smfc#43]
system: AMD EPYC 7713, 2x NVMe drives (no HDDs etc.).

Execution smfc.py on Debian 12 (kernel 6.1.0-27-amd64) fails while reading the temperature of NVMe drives - path to temp1_input is not correct. The correct path for the first drive is "/sys/class/nvme/nvme0/hwmon*/temp1_input".

With a modified search_str construction the script works as expected:

search_str = os.path.join("/sys/class/nvme", f"nvme{i}", "hwmon*/temp1_input")

**Comment by petersulyok** [comment]
Hi @olk, thanks for reporting this. Could you please recall the original configuration (disk name) and the error message you got?
I'd appreciate that. Thanks.

**Comment by petersulyok** [comment]
Hi @olk, this issues will be corrected in v3.6.0. A note on your suggestion:

`search_str = os.path.join("/sys/class/nvme", f"nvme{i}", "hwmon*/temp1_input")`

This suggestion works only if NVME disks are specified in the config file. Even in this situation it is not guaranteed that the proper disks will be referred in case of multiple NVME SSDs.
Thanks for reporting, again.

**Comment by olk** [comment]
ty
