### ISSUE TITLE
Allow swapping of CPU and HDD zones

### ISSUE THREAD

**Issue by matthuska** [petersulyok/smfc#7]
Would it be possible to add a config setting to swap the CPU and HDD/IO zones?

My current setup is to have the CPU fan on FAN A, and then case fans hooked up to FAN 1-4 to keep the hard drives cool. This is a swap of what is suggested by Supermicro, where FAN A+B are for IO, and FAN 1-4 are for the CPU, but in reading forums I think it is a common setup for people who are doing manual fan control using userspace scripts such as smfc.

**Comment by petersulyok** [comment]
The feature has been implemented in v2.3.0 release.
