### ISSUE TITLE
Are the tests safe to run in package building environment?

### ISSUE THREAD

**Issue by emansom** [petersulyok/smfc#9]
Are the tests safe to run in an package building environment?

As in, they do not touch the real physical IPMI on the host?

**Comment by petersulyok** [comment]
All tests, including smoke and unit tests, are relying on fake test data without touching IPMI or the HW.
The only difference is that smoke tests are using predefined test data and configuration from the `test` directory while unit tests are dynamically creating and deleting test data in `/tmp` folder. 

Only `bash` and `Python` is required for the execution. `ipmitool` and `smartctl` commands are substituted with shell scripts.

Unit test are also executed in github for each commit. So, I would say execution of the tests is safe.
